M48
; DRILL file {KiCad (6.0.1)} date Wed Jan 19 01:46:26 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-19T01:46:26+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X38.33Y-28.475
X38.33Y-33.325
T2
X35.3Y-28.175
X35.3Y-33.625
T0
M30
